---

# configure carbon

- name: write config files
  template:
    src: "{{ item.src }}"
    dest: "{{ carbon_confdir }}/{{ item.dest }}"
  loop:
    - { src: 'templates/carbon/carbon.conf.j2', dest: 'carbon.conf' }
    - { src: 'templates/carbon/storage-schemas.conf.j2', dest: 'storage-schemas.conf' }
    - { src: 'templates/carbon/storage-aggregation.conf.j2', dest: 'storage-aggregation.conf' }

      #- name: enable carbon service
      #  service:
      #    name: "{{ carbon_service }}"
      #    enabled: yes
      #  notify:
      #    - 'restart carbon cache'

- name: initialize database
  command: "PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb"

- name: collect static files
  command: "PYTHONPATH=/opt/graphite/webapp/ django-admin.py collectstatic --settings=graphite.settings"



