---

- name: install required packages
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ graphite_requirements }}'
  register: graphite_rpms_installed
  until: graphite_rpms_installed is success
  retries: 10
  delay: 2

- name: install graphite from pip
  pip:
    executable: "/bin/pip3.4"
    state: present
    name: "{{ item }}"
  loop: '{{ pip_packages }}'
  register: graphite_pip_installed
  until: graphite_pip_installed is success
  retries: 10
  delay: 2
