---

- name: install required packages
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ graphite_requirements }}'

- name: install graphite from pip
  pip:
    executable: "/bin/pip3.4"
    state: present
    name: "{{ item }}"
  loop: '{{ pip_packages }}'


